# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    working_directory: ~/bitcore
    steps:
      - checkout
      - run:
          name: Build service
          command: npm run test:ci:build
  unit:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    working_directory: ~/bitcore
    steps:
      - run:
          name: Unit Test Service
          command: npm run test:ci:unit

  integration:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    working_directory: ~/bitcore
    steps:
      - run:
          name: Integration Test Service
          command: npm run test:ci:integration

  coverage:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    working_directory: ~/bitcore
    steps:
      - run:
          name: Coverage
          command: npm run test:ci:coverage
